# Default values for Redoc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

env:
  PAGE_TITLE: ""
  PAGE_FAVICON: ""
  SPEC_URL: ""
  PORT: "80"

image:
  repository: redocly/redoc
  tag: v2.0.0-rc.74
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: NodePort
  ports: 
    port: 38080

# livenessProbe:
#   initialDelaySeconds: 5
#   timeoutSeconds: 5
#   periodSeconds: 10
#   failureThreshold: 3

ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/forwarded-for-header: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/x-forwarded-proto: "https"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
  hosts:
    - host: chart-example.local
  path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    memory: "2Gi"
  requests:
    memory: "512Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
