apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redoc.fullname" . }}
  labels:
    {{- include "redoc.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "redoc.name" . }}
    helm.sh/chart: {{ include "redoc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "redoc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "redoc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PAGE_TITLE
            value: {{ .Values.env.PAGE_TITLE | quote }}
          - name: PAGE_FAVICON
            value: {{ .Values.env.PAGE_FAVICON | quote }}
          - name: SPEC_URL
            value: {{ .Values.env.SPEC_URL | quote }}
          - name: PORT
            value: {{ .Values.env.PORT | quote }}
          # livenessProbe:
          #   httpGet:
          #     path: /ping
          #     port: {{ .Values.service.ports.port }}
          #   initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          #   timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          #   periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          #   failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}