apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "morpheus-worker.fullname" . }}
  labels:
    {{- include "morpheus-worker.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "morpheus-worker.name" . }}
    helm.sh/chart: {{ include "morpheus-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if not .values.autoscaling.enabled }}
  replicas: {{ .values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "morpheus-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "morpheus-worker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .values.image.repository }}:{{ .values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .values.image.pullPolicy }}
          env:
          - name: MORPHEUS_KEY
            value: {{ .values.env.MORPHEUS_KEY | quote }}
          - name: MORPHEUS_WORKER_KEY
            value: {{ .values.env.MORPHEUS_WORKER_KEY | quote }}
          - name: MORPHEUS_URL
            value: {{ .values.env.MORPHEUS_URL | quote }}
          - name: MORPHEUS_SELF_SIGNED
            value: {{ .values.env.MORPHEUS_SELF_SIGNED | quote }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .values.service.ports.port }}
            initialDelaySeconds: {{ .values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .values.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .values.livenessProbe.failureThreshold }}
          resources:
            {{- toYaml .values.resources | nindent 12 }}
      {{- with .values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}