apiVersion: v1
kind: Service
metadata:
  name: {{ include "morpheus-worker.fullname" . }}
  labels:
    {{- include "morpheus-worker.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "morpheus-worker.name" . }}
    helm.sh/chart: {{ include "morpheus-worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    {{- include "morpheus-worker.selectorLabels" . | nindent 4 }}
